[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "reprover"
version = "0.1"

[tool.setuptools]
py-modules = ["common"]

[tool.setuptools.packages.find]
include = ["retrieval*", "generation*", "prover*"]
